#!/usr/bin/env python3.6

import sys
import pygame

sys.path.append('/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages')
sys.path.append('src')

import logging
#import pygame

from loader import Loader
from proc import Proc


def __main__():
  pygame.init()
  root = logging.getLogger()
  root.setLevel(logging.DEBUG)
  
  ch = logging.StreamHandler(sys.stdout)
  ch.setLevel(logging.DEBUG)
  
  rom_path = "rom/tetris_world.gb";

  proc = Proc()
  loader = Loader()
  proc.ram[0x0000] = loader.load_rom(rom_path)

  size = width, height = 160, 144
  black = 0, 0, 0

  screen = pygame.display.set_mode(size)

  logging.debug("Starting main emulation loop");
  while 1:
    for event in pygame.event.get():
      if event.type == pygame.QUIT: sys.exit()

    proc.emulate_cycle()

    screen.fill(black)
    pygame.display.flip()

  return 0;

__main__()

